[server]
headless = true
address = "0.0.0.0"
port = 8501
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1e4078"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f5ff"
textColor = "#0d0d0d"

